format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/atmosphere/restart_dump.astart
  hashes:
    binhash: b63b24168f21aadce6fa6c0cc7f435e3
    md5: 4286e89fa0218c646155c73362871a3c
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/atmosphere/um.res.yaml
  hashes:
    binhash: f5be16a43f792ecc6c752e7b351cc141
    md5: 1c48fcc00d348365151147e9e50dcb7c
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/coupler/a2i.nc
  hashes:
    binhash: a0c96401b805768db529a4682964665e
    md5: 99a6e754374a95179d20ad09c0ef5c5f
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/coupler/i2a.nc
  hashes:
    binhash: a28944be3ffbda01fa55336bf2f49c65
    md5: 52035590ef86280485f8ddaa0fc431b1
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/coupler/o2i.nc
  hashes:
    binhash: 0cdcaa940ee66cf7cdcbd0abf8e10e2e
    md5: 41b02f3c60a3fbff573af8666c532203
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ice/cice_in.nml
  hashes:
    binhash: 81ce70e9e27b86ade3c57c28f5dc5ff3
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ice/ice.restart_file
  hashes:
    binhash: 9a67840c6c0aeb128553b1f27d3d5e4b
    md5: 6dd69c089650f9b3d288756e05897469
work/ice/RESTART/iced.3016-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ice/iced.3016-01-01-00000.nc
  hashes:
    binhash: 1db8e15169e622d0d06c523d5881f137
    md5: bc1335c8017738a08199181010d129bf
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ice/mice.nc
  hashes:
    binhash: 140f560699f4b8d3d44236d25acb3710
    md5: 7d0970ba2ab400999cf3f139889d3a88
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_age.res.nc
  hashes:
    binhash: 6b6d0e881d87136a58e3818107ab92cc
    md5: 73964553659cdaa58ec438073dc9b6fb
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: e890032abfed1a7f09432fc1548c7976
    md5: a4ac211b120ad5cd9fd7e46e48ec7e03
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: f837ab465dd322202d73076edad9c6bc
    md5: ae1de758d8de70f4e4851a47a3bc5720
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_density.res.nc
  hashes:
    binhash: a791c0285bc8b13547df0398a10ab5b2
    md5: 1491a1018a61bb36cc3c1d5213569da4
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 7c3f722e9dd0529778d3c97183cbc308
    md5: a954f31ae1ed19168255faaf6b70e78a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5a26e6ab7d17f554a15558fbc776e86f
    md5: bdba7dc2e73991cb42087980ee72b6d6
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_neutral.res.nc
  hashes:
    binhash: f62cb7f206da9575f0fedfe6e3c1a1c6
    md5: e4a4c0c7348b1baad7729fc35bde7597
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 4e145425db5db6bcac5581063d289c49
    md5: 3895d1b3bf05fcbe92c02f1046b6eecd
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_sbc.res.nc
  hashes:
    binhash: dfb004df5c8d8cdcfc2a7b410d6cee1f
    md5: b7fe89669b14fe7cb7ceab09279e8c2f
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: f91a3ea07de62c39716b80c64f1e8eb9
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_solo.res
  hashes:
    binhash: 98de405698ff7926ca78562a2b4f9fbb
    md5: 38dc2383f5c6f0fb6297c724cf687143
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: 8ec17400fb7bd6d344a3cf988b4fc8e5
    md5: 58fa7a2bd93d3058bbd79b782cbea753
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 18095fb9153361d6f31570e4805aa6c1
    md5: 0aa381c9f02fe368a7f9343d550bda37
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_tracer.res
  hashes:
    binhash: 3380bb8d1af27faef2761ba830475cad
    md5: 2a383a7582c28ba97e04fb2fa652b517
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_velocity.res.nc
  hashes:
    binhash: a49dae696ed10d57acfa6462727f803c
    md5: 08b4624bda0f42bb32e1d6d2cc1e2450
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: a6bef422148799f0207151ab59dd5142
    md5: 7bfd6f28d5536c3bc343fefca7d6a8e6
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 5feee69747e5d01fd347aaf060111e50
    md5: bbe01689e7139016d8cb001c7673ed48
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/txz599/access-esm/archive/test_pi_plss_02-expt-a9acd03a/restart138/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 7082b2f7bf6ca127a9552e13fc645aef
    md5: 2b850a77175c0072f00ad04211dc8676
