format: yamanifest
version: 1.0
---
work/atmosphere/restart_dump.astart:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/atmosphere/restart_dump.astart
  hashes:
    binhash: 848d9f26ea14a6b5d838eb1746730575
    md5: 08761561ae5c608118ef3a7a7ffce758
work/atmosphere/um.res.yaml:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/atmosphere/um.res.yaml
  hashes:
    binhash: c91ebc7be86c69db233cd3d77fcb1438
    md5: 9afc8fa3be7abd7f1a016741998598c2
work/coupler/a2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/coupler/a2i.nc
  hashes:
    binhash: ab7e9a2ee4b1c4dce3cd6ae76bdf71df
    md5: 02898bf5dc8de5ae62d325f07ac270cf
work/coupler/i2a.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/coupler/i2a.nc
  hashes:
    binhash: 9dedc4c22f6093f1d3cfb37f820e765f
    md5: 3203e35fdc4c6c4bb98a5795cfb9753f
work/coupler/o2i.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/coupler/o2i.nc
  hashes:
    binhash: f6fe28ea5cce7a854552935cbfeffc93
    md5: 59d9bfd54c6f6dfbccfac42e64182646
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ice/cice_in.nml
  hashes:
    binhash: 1487b28292c0e4bbd517af66ffebaf06
    md5: f27d1348905f57fd090b3add437f7d49
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ice/ice.restart_file
  hashes:
    binhash: 34e9dc9cce53010340f5b423c2ea9e2b
    md5: 839b815b07bcd0ec4d1d8f1e3b163597
work/ice/RESTART/iced.0078-01-01-00000.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ice/iced.0078-01-01-00000.nc
  hashes:
    binhash: e4c96e44622890541cd480b8f0124108
    md5: 898f8131752e0e4055fdc09db3cf45eb
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ice/mice.nc
  hashes:
    binhash: b664a6259b00de6f4effbc9c4a6f42c8
    md5: f82d7935a94b457ab91f090a84468834
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_age.res.nc
  hashes:
    binhash: 415a122fc06858b87c2302be628051f0
    md5: 056c1fb4be8380a94441b213239c289c
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6cf850f596f4c76186e51b625b9999b5
    md5: cb8ad560fba809d442a11f668adcfc52
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3b8d785eda7bbec500428431933425d4
    md5: e5c3ef124e123d3c3f6dec8bb1b03843
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_density.res.nc
  hashes:
    binhash: 2a811c13c8e2a1d923ea4ee7376a5fbb
    md5: cb577c91aef81afda39e6f9f18bc573f
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 24348f2532c2f98672e9388b5f6283ba
    md5: bfaff917c1702dfa508336dad021404a
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: bcb0ffe2a45a3038a0fa4aeb3230b870
    md5: 135d56659f667127b080b383566df378
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 746397f0ae4d9205e17eca0ba85519ab
    md5: c00f7baf48bbbb9a29a471f29a51be6c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: a8f54f64de4a8b84456dbd68c1f924a6
    md5: dced5ef6fc5ce659b9351a666cdebb88
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e83fce9e7c78d3db75c56be59d1a70d4
    md5: d0f47b5da312b5d233cdb9be57d4b93d
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: ea0d98387ec2c0d3b1abe512ae22d4cf
    md5: 5ff03bcf0c1ee96e07df055846ed2d04
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_solo.res
  hashes:
    binhash: 0311050469dd3adc15ef863cf4977d05
    md5: af76cb2089ccc7e88e365134df1767f6
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: e0031c3247d853b6df8d0deb7291bd13
    md5: 5032add40b60e737c6a2c2c015094150
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_thickness.res.nc
  hashes:
    binhash: f50e3ba9cae7009afbf1ee81ee2b87ed
    md5: 4a2fc9d67d9dd53c3270a77587547a6e
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_tracer.res
  hashes:
    binhash: adb8aa39f1c6302ea7bb43054a7dde6a
    md5: f9f851a605e6ba32f9bb98e3d98184eb
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 105703c4f2d3b6e0dd21cc423e4eb53d
    md5: 427b2f1aa6aec874ca72f222b3ac00b6
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: aca310b72907401a43a43d1112c2fb49
    md5: c7fad43cc4d49283658bc26a8535e93e
work/ocean/INPUT/ocean_wombatlite.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_wombatlite.res.nc
  hashes:
    binhash: 3470c672c200bf342b50d4cc2449321e
    md5: 11360dcb281574843be54e3a47e99321
work/ocean/INPUT/ocean_wombatlite_airsea_flux.res.nc:
  fullpath: /scratch/p66/jxs599/access-esm/archive/Feb26-PI-CNP-concentrations-Feb26-PI-CNP-concentrations-85a84cd7/restart076/ocean/ocean_wombatlite_airsea_flux.res.nc
  hashes:
    binhash: 61ff61bbe17b310e837d1aca99fc2bc5
    md5: 6f474c09baab4740047fe225891a0c3b
